// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Switchback.Data;

namespace Switchback.Migrations
{
    [DbContext(typeof(SwitchbackAPIDbContext))]
    partial class SwitchbackAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Switchback.Models.DefaultReturn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message");

                    b.HasKey("ID");

                    b.ToTable("DefaultReturns");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Message = "Hello world"
                        },
                        new
                        {
                            ID = 2,
                            Message = "Hello Website"
                        });
                });

            modelBuilder.Entity("Switchback.Models.UserRating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TrailInfoID");

                    b.HasKey("ID");

                    b.ToTable("UserRating");
                });
#pragma warning restore 612, 618
        }
    }
}
