// <auto-generated />
using System;
using API_SwitchBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_SwitchBack.Migrations
{
    [DbContext(typeof(SwitchbackAPIDbContext))]
    [Migration("20190416214130_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_SwitchBack.Models.Trail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ascent");

                    b.Property<string>("conditionDate");

                    b.Property<string>("conditionDetails");

                    b.Property<string>("conditionStatus");

                    b.Property<int>("descent");

                    b.Property<string>("difficulty");

                    b.Property<int>("high");

                    b.Property<string>("imgMedium");

                    b.Property<string>("imgSmall");

                    b.Property<string>("imgSmallMed");

                    b.Property<string>("imgSqSmall");

                    b.Property<float>("latitude");

                    b.Property<float>("length");

                    b.Property<string>("location");

                    b.Property<float>("longitude");

                    b.Property<int>("low");

                    b.Property<string>("name");

                    b.Property<int>("starVotes");

                    b.Property<float>("stars");

                    b.Property<string>("summary");

                    b.Property<string>("type");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("Trail");
                });

            modelBuilder.Entity("API_SwitchBack.Models.UserRatings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rating");

                    b.Property<int>("TrailInfoID");

                    b.Property<int?>("Trailid");

                    b.HasKey("ID");

                    b.HasIndex("Trailid");

                    b.ToTable("UserRatings");
                });

            modelBuilder.Entity("API_SwitchBack.Models.UserRatings", b =>
                {
                    b.HasOne("API_SwitchBack.Models.Trail", "Trail")
                        .WithMany("UserRatings")
                        .HasForeignKey("Trailid");
                });
#pragma warning restore 612, 618
        }
    }
}
